# Site settings
title: Steven Wonders
email: steve@sixgables.com
description: "This is a description.  It gives details and explains things."
baseurl: ""
url: "http://greenbes.github.io"

# Build settings
markdown: kramdown
permalink: pretty
